      - name: Build Project
        run: npm run build
        env:
          CI: false # Agar build tidak gagal jika ada warning

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # Pastikan ini './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
